<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">

    <a class="navbar-brand" href="./">
        <img src="https://tyrolium.fr/Contenu/Image/Vturias Site.png" width="30" height="30" class="d-inline-block align-top" alt="">
        Vturias
    </a>

    <button class="navbar-toggler-perso" type="button">
        <span class="material-symbols-outlined">menu</span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="./">Accueil <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled">
                     Boutique <span class="badge badge-pill badge-secondary">SOON</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="legal.php">Mentions Légales</a>
            </li>
            <li class="nav-item active nav-reseau">
                <div class="nav-item active">
                    <a class="nav-link" href="https://twitter.com/Vturias_Project"><i class="fa-brands fa-x-twitter"></i></a>
                </div>
                <div class="nav-item active">
                    <a class="nav-link" href="https://discord.gg/nUc8kED8st"><i class="fa-brands fa-discord"></i></a>
                </div>
                <div class="nav-item active">
                    <a class="nav-link" href="https://www.instagram.com/vturias_project/"><i class="fa-brands fa-instagram"></i></a>
                </div>
                <div class="nav-item active">
                    <a class="nav-link" href="https://www.youtube.com/@VturiasProject"><i class="fa-brands fa-youtube"></i></a>
                </div>
                <div class="nav-item active">
                    <a class="nav-link" href="https://www.tiktok.com/@vturias_project"><i class="fa-brands fa-tiktok"></i></a>
                </div>
                <div class="nav-item active">
                    <a class="nav-link" href="https://www.linkedin.com/company/vturias/"><i class="fa-brands fa-linkedin-in"></i></a>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="https://twitter.com/Vturias_Project"><i class="fa-brands fa-x-twitter"></i></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="https://discord.gg/nUc8kED8st"><i class="fa-brands fa-discord"></i></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="https://www.instagram.com/vturias_project/"><i class="fa-brands fa-instagram"></i></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="https://www.youtube.com/@VturiasProject"><i class="fa-brands fa-youtube"></i></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="https://www.tiktok.com/@vturias_project"><i class="fa-brands fa-tiktok"></i></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="https://www.linkedin.com/company/vturias/"><i class="fa-brands fa-linkedin-in"></i></a>
            </li>
        </ul>
    </div>

</nav>

<script>

    document.addEventListener("DOMContentLoaded", function() {
        const navbarToggler = document.querySelector(".navbar-toggler-perso");
        const navbarCollapse = document.querySelector(".navbar-collapse");

        navbarToggler.addEventListener("click", function() {
            navbarCollapse.classList.toggle("show");
        });
    });

</script>
